"use client";

import React, { useMemo, useState } from "react";
import Script from "next/script";

type Product = { id: string; name: string; price: number; stock: number; image: string; desc: string };
type Cart = Record<string, number>;

const PRODUCTS: Product[] = [
  { id: "prod_1", name: "Akruti Collection Oxidised Navratri Damini Maangtikka", price: 599, stock: 20, image: "/item1.jpg", desc: "Stunning Oxidised Plated Finish." },
  { id: "prod_2", name: "Etnico 18k Gold Plated Kundan Kamarband/Waist Chain", price: 426, stock: 20, image: "/item2.jpg", desc: "White Stone Studded Belly Chain for Women." },
  { id: "prod_3", name: "Palak Art Heritage Austrian Stone Pearl Necklace Set", price: 1176, stock: 20, image: "/item3.jpg", desc: "White Pearl and Beads with Austrian Stone." },
  { id: "prod_4", name: "Maharani Jewels Oxidised Pota Stone Pearl Jhumki", price: 305, stock: 20, image: "/item4.jpg", desc: "Black Pearl Jhumki Earrings." },
  { id: "prod_5", name: "Darshana Jewels Oxidised Plated Dangler Earrings", price: 77, stock: 20, image: "/item5.jpg", desc: "Oxidised Dangler Earrings." },
  { id: "prod_6", name: "Darshana Jewels Oxidised Plated Dangler Earrings Small", price: 52, stock: 20, image: "/item6.jpg", desc: "Oxidised Dangler Earrings." },
];

export default function TrendyJewelleryStore() {
  const [cart, setCart] = useState<Cart>({});
  const [checkout, setCheckout] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", phone: "", address: "", pincode: "" });
  const total = useMemo(() => Object.entries(cart).reduce((sum, [id, qty]) => sum + (PRODUCTS.find(p => p.id === id)?.price ?? 0) * qty, 0), [cart]);
  const count = Object.values(cart).reduce((sum, n) => sum + n, 0);
  const change = (id: string, delta: number) => setCart(c => { const product = PRODUCTS.find(p => p.id === id); const next = (c[id] ?? 0) + delta; if (!product || next > product.stock) return c; const result = { ...c }; if (next > 0) result[id] = next; else delete result[id]; return result; });
  const setField = (key: keyof typeof form, value: string) => setForm(f => ({ ...f, [key]: value }));
  const complete = form.name.trim().length >= 2 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email) && /^\d{10}$/.test(form.phone) && form.address.trim().length >= 8 && /^\d{6}$/.test(form.pincode) && total > 0;
  const pay = async () => { if (!complete) return; try { const r = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, cart, amount: Math.round(total * 1.03 * 100) }) }); const data = await r.json(); if (!r.ok || !data.orderId || !data.keyId || !window.Razorpay) throw new Error(); new window.Razorpay({ key: data.keyId, amount: data.amount, currency: data.currency || "INR", name: "TRENDY JEWELLERY", order_id: data.orderId, prefill: { name: form.name, email: form.email, contact: form.phone }, theme: { color: "#b38728" }, handler: response => { alert(`Order confirmed!\nPayment ID: ${response.razorpay_payment_id}`); setCart({}); setCheckout(false); } }).open(); } catch { alert("Checkout is ready, but the payment server is not connected yet."); } };

  return <main className="store">
    <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" />
    <div className="announcement">✨ NATIONWIDE SECURE DELIVERY ✨ 100% AUTHENTIC BRANDED JEWELLERY ✨ FREE SHIPPING ON PREPAID ORDERS ✨</div>
    <header><h1 onClick={() => setCheckout(false)}>TRENDY <span>JEWELLERY</span></h1><button onClick={() => total && setCheckout(true)}>CART ({count}) • ₹{total.toLocaleString("en-IN")}</button></header>
    <div className="content">{!checkout ? <><section className="hero"><h2>Elegance, <span>Redefined.</span></h2><p>Premium jewellery selected for your special moments.</p></section><section className="products">{PRODUCTS.map(p => <article className="card" key={p.id}><div className="photo"><img src={p.image} alt={p.name}/>{p.price <= 500 && <b>Price Rising Soon</b>}</div><h3>{p.name}</h3><p>{p.desc}</p><strong>₹{p.price.toLocaleString("en-IN")}</strong><div className="actions">{cart[p.id] ? <div className="quantity"><button onClick={() => change(p.id, -1)}>−</button>{cart[p.id]}<button onClick={() => change(p.id, 1)}>+</button></div> : <button onClick={() => change(p.id, 1)}>ADD TO CART</button>}<button className="buy" onClick={() => { change(p.id, 1); setCheckout(true); }}>BUY NOW</button></div></article>)}</section>{total > 0 && <button className="checkout" onClick={() => setCheckout(true)}>PROCEED TO CHECKOUT (₹{total.toLocaleString("en-IN")})</button>}</> : <section className="panel"><button className="back" onClick={() => setCheckout(false)}>← Back to Shop</button><h2>Checkout</h2><div className="summary">{Object.entries(cart).map(([id, qty]) => { const p = PRODUCTS.find(x => x.id === id)!; return <div className="row" key={id}><span>{p.name}<br/><b>₹{p.price} × {qty}</b></span><div className="quantity"><button onClick={() => change(id, -1)}>−</button>{qty}<button onClick={() => change(id, 1)}>+</button></div></div>})}</div><h3>Shipping Details</h3><div className="form">{(["name", "email", "phone", "address", "pincode"] as const).map(key => <input key={key} type={key === "email" ? "email" : "text"} placeholder={key[0].toUpperCase() + key.slice(1)} value={form[key]} onChange={e => setField(key, e.target.value.replace(key === "phone" || key === "pincode" ? /\D/g : /.^/g, ""))}/>)}</div><div className="billing"><div>Subtotal <b>₹{total.toFixed(2)}</b></div><div>GST (3%) <b>₹{(total * .03).toFixed(2)}</b></div><div className="grand">Total <b>₹{(total * 1.03).toFixed(2)}</b></div></div><button className="pay" disabled={!complete} onClick={pay}>{complete ? `SECURELY PAY ₹${(total * 1.03).toFixed(2)}` : "COMPLETE FORM TO PAY"}</button></section>}</div>
    <a className="whatsapp" href="https://wa.me/919279566257" target="_blank" rel="noreferrer">💬 WhatsApp Support</a>
    <style jsx global>{`*{box-sizing:border-box}body{margin:0;font-family:Arial;color:#111}.store{min-height:100vh;background:#fcfcfc}.announcement{padding:10px;text-align:center;color:#d4af37;background:#111;font-size:12px;font-weight:bold;letter-spacing:1px}header{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:center;padding:20px 5%;background:#fff;border-bottom:1px solid #eee}h1{margin:0;font-size:26px;cursor:pointer}h1 span,.hero span,.card strong{color:#b38728}header button,.buy,.checkout,.pay{color:#fff;background:#111;border:0;border-radius:4px;padding:13px 20px;font-weight:bold;cursor:pointer}.content{max-width:1200px;margin:auto;padding:50px 20px}.hero{text-align:center;margin-bottom:45px}.hero h2{font-size:34px;font-weight:400}.products{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:30px}.card,.panel{padding:16px;background:#fff;border:1px solid #eee;border-radius:10px}.photo{height:300px;position:relative}.photo img{width:100%;height:100%;object-fit:cover}.photo b{position:absolute;top:10px;right:10px;padding:8px;background:#111;color:#d4af37;font-size:11px}.card h3{min-height:45px}.card p{color:#777;min-height:35px}.card>strong{display:block;font-size:20px;margin:18px 0}.actions,.quantity{display:flex;gap:8px;align-items:center}.actions>button{flex:1;padding:12px;border:1px solid #ccc;background:#fafafa;cursor:pointer;font-size:11px;font-weight:bold}.actions .buy{background:#b38728;color:#fff;border-color:#b38728}.quantity{justify-content:space-between;border:1px solid #111;padding:4px;flex:1}.quantity button{background:none;border:0;font-size:20px;cursor:pointer}.checkout{display:block;margin:45px auto;background:#b38728}.panel{max-width:650px;margin:auto;padding:35px}.back{border:0;background:none;color:#b38728;font-weight:bold;cursor:pointer}.summary,.billing{padding:20px;background:#fafafa;border:1px solid #eee;margin:20px 0}.row,.billing div{display:flex;justify-content:space-between;gap:15px;padding:14px 0;border-bottom:1px solid #eee}.form{display:grid;gap:14px}.form input{padding:14px;border:1px solid #ddd;border-radius:4px;font-size:15px}.grand{font-size:21px;border:0!important}.pay{width:100%;background:#b38728}.pay:disabled{background:#ddd;color:#888;cursor:not-allowed}.whatsapp{position:fixed;right:20px;bottom:20px;padding:14px 18px;background:#25d366;color:#fff;border-radius:30px;text-decoration:none;font-weight:bold}@media(max-width:600px){header{padding:16px}h1{font-size:18px}.panel{padding:22px 16px}.content{padding:30px 15px}}`}</style>
  </main>;
}