"use client";
import React, { useState, useEffect } from 'react';
import Script from 'next/script';

const PRODUCTS = [
	{ id: 'prod_1', name: 'Akruti Collection Oxidised Navratri Damini Maangtikka', price: 428, stock: 20, images: ['/item1.jpg', '/item1-alt.jpg'], desc: 'Stunning Oxidised Plated Finish.' },
	{ id: 'prod_2', name: 'Etnico 18k Gold Plated Kundan Kamarband/Waist Chain', price: 304, stock: 20, images: ['/item2.jpg', '/item2-alt.jpg'], desc: 'White Stone Studded Belly Chain for Women (B003W).' },
	{ id: 'prod_3', name: 'Palak Art Heritage Austrian Stone Pearl Necklace Set', price: 840, stock: 20, images: ['/item3.jpg', '/item3-alt.jpg'], desc: 'White Pearl and Beads with Austrian Stone.' },
	{ id: 'prod_4', name: 'Maharani Jewels Oxidised Pota Stone Pearl Jhumki', price: 218, stock: 20, images: ['/item4.jpg', '/item4-alt.jpg'], desc: 'Black Pearl Jhumki Earrings.' },
	{ id: 'prod_5', name: 'Darshana Jewels Oxidised Plated Dangler Earrings (Large)', price: 55, stock: 20, images: ['/item5.jpg', '/item5-alt.jpg'], desc: 'Oxidised Dangler Earrings.' },
	{ id: 'prod_6', name: 'Darshana Jewels Oxidised Plated Dangler Earrings (Small)', price: 37, stock: 20, images: ['/item6.jpg', '/item6-alt.jpg'], desc: 'Oxidised Dangler Earrings.' }
];

export default function TrendyJewelleryStore() {
	const [cart, setCart] = useState<{ [key: string]: number }>({});
	const [isCheckingOut, setIsCheckingOut] = useState(false);
	const [currentImageIndex, setCurrentImageIndex] = useState(0);
	const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState('');
	const [altPhone, setAltPhone] = useState(''); const [address, setAddress] = useState(''); const [landmark, setLandmark] = useState(''); const [pincode, setPincode] = useState('');
	const [loading, setLoading] = useState(false); const [taxes, setTaxes] = useState({ cgst: 0, sgst: 0, igst: 0, grandTotal: 0 });
	const [isCalculated, setIsCalculated] = useState(false); const [paymentStatus, setPaymentStatus] = useState('');
	const SUPPORT_NUMBER = '919999999999';
	const cartTotal = Object.keys(cart).reduce((total, id) => { const product = PRODUCTS.find(p => p.id === id); return total + (product ? product.price * cart[id] : 0); }, 0);
	const cartItemCount = Object.values(cart).reduce((a, b) => a + b, 0);

	useEffect(() => { const timer = setInterval(() => setCurrentImageIndex(prev => (prev + 1) % 2), 3000); return () => clearInterval(timer); }, []);
	const updateQuantity = (id: string, delta: number) => { const product = PRODUCTS.find(p => p.id === id); if (!product) return; setCart(prev => { const next = (prev[id] || 0) + delta; if (next > product.stock) { alert(`Sorry, we only have ${product.stock} of ${product.name} left in stock!`); return prev; } if (next <= 0) { const result = { ...prev }; delete result[id]; return result; } return { ...prev, [id]: next }; }); };
	const handlePincodeChange = async (e: React.ChangeEvent<HTMLInputElement>) => { const val = e.target.value.replace(/\D/g, ''); setPincode(val); if (val.length !== 6 || !cartTotal) { setIsCalculated(false); return; } setLoading(true); try { const res = await fetch('/api/calculate-tax', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ amount: cartTotal, pincode: val }) }); const data = await res.json(); setTaxes({ cgst: data.cgst, sgst: data.sgst, igst: data.igst, grandTotal: data.total }); setIsCalculated(true); } finally { setLoading(false); } };
	const isFormComplete = Boolean(name && email && phone.length >= 10 && address && isCalculated);
	const handlePayment = async () => { if (!isFormComplete || !(window as any).Razorpay) return alert('Payment system loading. Please wait.'); setPaymentStatus('Initializing secure checkout...'); try { const res = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ amount: taxes.grandTotal }) }); const orderData = await res.json(); const rzp = new (window as any).Razorpay({ key: orderData.keyId, amount: orderData.amount, currency: orderData.currency, name: 'TRENDY JEWELLERY', order_id: orderData.orderId, prefill: { name, email, contact: phone }, theme: { color: '#d4af37' }, handler: async (response: any) => { const verifyRes = await fetch('/api/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(response) }); if ((await verifyRes.json()).success) { alert(`🎉 Payment Verified! Order ID: ${response.razorpay_payment_id}`); setCart({}); setIsCheckingOut(false); } } }); rzp.open(); } catch { setPaymentStatus('Payment error.'); } };
	const inputStyle = { width: '100%', padding: '14px', backgroundColor: '#fafafa', border: '1px solid #e5e5e5', borderRadius: '8px', fontSize: '14px', outline: 'none', marginBottom: '16px' };
	return <main style={{ minHeight: '100vh', backgroundColor: '#fff', color: '#111', fontFamily: 'sans-serif' }}><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" /><header style={{ padding: '20px 40px', display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #eaeaea' }}><h1 onClick={() => setIsCheckingOut(false)} style={{ color: '#d4af37', cursor: 'pointer' }}>TRENDY JEWELLERY</h1><b onClick={() => cartTotal > 0 && setIsCheckingOut(true)}>🛒 Cart ({cartItemCount}) - ₹{cartTotal.toLocaleString('en-IN')}</b></header><a href={`https://wa.me/${SUPPORT_NUMBER}`} target="_blank" rel="noreferrer">💬 Chat on WhatsApp</a><div style={{ padding: '40px 20px', maxWidth: '1200px', margin: 'auto' }}>{!isCheckingOut ? <><h2 style={{ textAlign: 'center', fontSize: '36px' }}>Elegance, Redefined.</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '40px' }}>{PRODUCTS.map(product => <div key={product.id} style={{ border: '1px solid #f0f0f0', padding: '24px' }}><img src={product.images[currentImageIndex % product.images.length]} alt={product.name} style={{ width: '100%', height: '300px', objectFit: 'cover' }} /><h3>{product.name}</h3><p>{product.desc}</p><b>₹{product.price.toLocaleString('en-IN')}</b><button onClick={() => updateQuantity(product.id, 1)} style={{ display: 'block', marginTop: '20px', padding: '12px', width: '100%' }}>{cart[product.id] ? `${cart[product.id]} in cart — Add one` : 'Add to Cart'}</button></div>)}</div>{cartTotal > 0 && <button onClick={() => setIsCheckingOut(true)}>Proceed to Checkout (₹{cartTotal.toLocaleString('en-IN')})</button>}</> : <div style={{ maxWidth: '600px', margin: 'auto' }}><button onClick={() => setIsCheckingOut(false)}>← Back to Shop</button><h2>Secure Checkout</h2><input placeholder="Full Name" value={name} onChange={e => setName(e.target.value)} style={inputStyle} /><input placeholder="Email Address" value={email} onChange={e => setEmail(e.target.value)} style={inputStyle} /><input placeholder="Primary Phone" value={phone} onChange={e => setPhone(e.target.value.replace(/\D/g, ''))} style={inputStyle} /><input placeholder="Full Street Address" value={address} onChange={e => setAddress(e.target.value)} style={inputStyle} /><input maxLength={6} placeholder="6-Digit Pincode" value={pincode} onChange={handlePincodeChange} style={inputStyle} /><p>Grand Total: ₹{taxes.grandTotal.toFixed(2)}</p><button onClick={handlePayment} disabled={!isFormComplete || loading}>{paymentStatus || 'Pay Securely'}</button></div>}</div></main>;
}
